version: "3.2"
services:
  server:
    container_name: server-go
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - localstack
    networks:
      - backend
      
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=sns,sqs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
        - backend
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack/"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  backend:
    driver: bridge